apigee_edge_debug.settings:
  type: config_object
  mapping:
    formatter:
      type: string
    log_message_format:
      type: text
    mask_organization:
      type: boolean
    remove_credentials:
      type: boolean
